2021-10-03 12:34:59,171 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 12:34:59] "GET /addjob HTTP/1.1" 200 -
2021-10-03 12:35:00,195 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 12:35:00] "POST /addjob HTTP/1.1" 200 -
2021-10-03 12:35:37,633 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 12:35:37] "GET /addjob HTTP/1.1" 200 -
2021-10-03 12:35:47,570 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 12:35:47] "POST /addjob HTTP/1.1" 200 -
2021-10-03 12:46:20,572 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 12:46:20] "GET /addjob HTTP/1.1" 200 -
2021-10-03 12:46:26,930 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 12:46:26] "POST /addjob HTTP/1.1" 200 -
2021-10-03 13:04:17,105 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 13:04:17] "GET /addjob HTTP/1.1" 200 -
2021-10-03 13:04:18,281 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 13:04:18] "POST /addjob HTTP/1.1" 200 -
2021-10-03 13:08:45,135 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 13:08:45] "GET /addjob HTTP/1.1" 200 -
2021-10-03 13:08:46,492 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 13:08:46] "POST /addjob HTTP/1.1" 200 -
2021-10-03 13:09:35,625 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 13:09:35] "GET /addjob HTTP/1.1" 200 -
2021-10-03 13:09:39,875 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 13:09:39] "POST /addjob HTTP/1.1" 200 -
2021-10-03 13:10:04,474 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 13:10:04] "GET /addjob HTTP/1.1" 200 -
2021-10-03 13:12:51,136 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 13:12:51] "GET /job HTTP/1.1" 200 -
2021-10-03 13:12:52,440 - webapp - ERROR - Exception on /listjobs [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-ui-service/webapp/webapp.py", line 76, in listjobs
    allJobsList = jobUIService.get_all_jobs()
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-ui-service/webapp/jobUIService.py", line 24, in get_all_jobs
    responseData = json.loads(jobs.content)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-10-03 13:12:52,442 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 13:12:52] "[35m[1mGET /listjobs HTTP/1.1[0m" 500 -
2021-10-03 13:14:42,239 - webapp - ERROR - Exception on /listjobs [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-ui-service/webapp/webapp.py", line 78, in listjobs
    return render_template("jobList.html", allJobsList=allJobsList)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-ui-service/webapp/templates/jobList.html", line 1, in top-level template code
    {% extends "candidate.html" %}
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-ui-service/webapp/templates/candidate.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-ui-service/webapp/templates/base.html", line 58, in top-level template code
    {% block content %}
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-ui-service/webapp/templates/jobList.html", line 17, in block 'content'
    {% for job in allJobsList %}
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/runtime.py", line 468, in __init__
    self._iterator = self._to_iterator(iterable)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/runtime.py", line 476, in _to_iterator
    return iter(iterable)
TypeError: 'NoneType' object is not iterable
2021-10-03 13:14:42,244 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 13:14:42] "[35m[1mGET /listjobs HTTP/1.1[0m" 500 -
2021-10-03 13:19:39,876 - webapp - ERROR - Exception on /listjobs [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-ui-service/webapp/webapp.py", line 76, in listjobs
    allJobsList = jobUIService.get_all_jobs()
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-ui-service/webapp/jobUIService.py", line 24, in get_all_jobs
    responseData = json.loads(jobs.content)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-10-03 13:19:39,878 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 13:19:39] "[35m[1mGET /listjobs HTTP/1.1[0m" 500 -
2021-10-03 13:20:42,925 - webapp - ERROR - Exception on /listjobs [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-ui-service/webapp/webapp.py", line 78, in listjobs
    return render_template("jobList.html", allJobsList=allJobsList)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-ui-service/webapp/templates/jobList.html", line 1, in top-level template code
    {% extends "candidate.html" %}
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-ui-service/webapp/templates/candidate.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-ui-service/webapp/templates/base.html", line 58, in top-level template code
    {% block content %}
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-ui-service/webapp/templates/jobList.html", line 17, in block 'content'
    {% for job in allJobsList %}
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/runtime.py", line 468, in __init__
    self._iterator = self._to_iterator(iterable)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/runtime.py", line 476, in _to_iterator
    return iter(iterable)
TypeError: 'NoneType' object is not iterable
2021-10-03 13:20:42,929 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 13:20:42] "[35m[1mGET /listjobs HTTP/1.1[0m" 500 -
2021-10-03 13:21:39,280 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 13:21:39] "GET /addjob HTTP/1.1" 200 -
2021-10-03 13:21:57,531 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 13:21:57] "POST /addjob HTTP/1.1" 200 -
2021-10-03 13:22:43,455 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 13:22:43] "GET /addjob HTTP/1.1" 200 -
2021-10-03 13:22:46,272 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 13:22:46] "GET /job HTTP/1.1" 200 -
2021-10-03 13:22:47,658 - webapp - ERROR - Exception on /listjobs [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-ui-service/webapp/webapp.py", line 78, in listjobs
    return render_template("jobList.html", allJobsList=allJobsList)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-ui-service/webapp/templates/jobList.html", line 1, in top-level template code
    {% extends "candidate.html" %}
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-ui-service/webapp/templates/candidate.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-ui-service/webapp/templates/base.html", line 58, in top-level template code
    {% block content %}
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-ui-service/webapp/templates/jobList.html", line 17, in block 'content'
    {% for job in allJobsList %}
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/runtime.py", line 468, in __init__
    self._iterator = self._to_iterator(iterable)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/runtime.py", line 476, in _to_iterator
    return iter(iterable)
TypeError: 'NoneType' object is not iterable
2021-10-03 13:22:47,659 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 13:22:47] "[35m[1mGET /listjobs HTTP/1.1[0m" 500 -
2021-10-03 13:25:20,820 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 13:25:20] "GET /listjobs HTTP/1.1" 200 -
2021-10-03 13:31:32,602 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 13:31:32] "GET /candidate HTTP/1.1" 200 -
2021-10-03 13:31:34,048 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 13:31:34] "GET /listcandidates HTTP/1.1" 200 -
2021-10-03 13:32:52,983 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-10-03 13:33:11,900 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 13:33:11] "GET /listcandidates HTTP/1.1" 200 -
2021-10-03 13:41:18,451 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 13:41:18] "GET /job HTTP/1.1" 200 -
2021-10-03 13:41:20,018 - webapp - ERROR - Exception on /listjobs [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-ui-service/webapp/webapp.py", line 76, in listjobs
    allJobsList = jobUIService.get_all_jobs()
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-ui-service/webapp/jobUIService.py", line 24, in get_all_jobs
    responseData = json.loads(jobs.content)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-10-03 13:41:20,021 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 13:41:20] "[35m[1mGET /listjobs HTTP/1.1[0m" 500 -
2021-10-03 13:42:22,109 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 13:42:22] "GET /listjobs HTTP/1.1" 200 -
2021-10-03 13:43:36,206 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 13:43:36] "GET /job HTTP/1.1" 200 -
2021-10-03 13:43:37,609 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 13:43:37] "GET /addjob HTTP/1.1" 200 -
2021-10-03 13:43:54,019 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 13:43:54] "POST /addjob HTTP/1.1" 200 -
2021-10-03 13:43:56,899 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 13:43:56] "GET /addjob HTTP/1.1" 200 -
2021-10-03 13:43:58,203 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 13:43:58] "GET /job HTTP/1.1" 200 -
2021-10-03 13:43:59,459 - werkzeug - INFO - 127.0.0.1 - - [03/Oct/2021 13:43:59] "GET /listjobs HTTP/1.1" 200 -
